### ISSUE TITLE
GitHub Repository Not Synchronised with Posted Website

### ISSUE THREAD

**Issue by rei-vilo** [energia/energia.nu#14]
The GitHub repository is not synchronised with the posted website.

Example:

+ https://github.com/energia/energia.nu/blob/master/content/top/download.adoc does not mention new release 1.8.7E20

<img width="1440" alt="capture 2018-10-06 a 08 53 45" src="https://user-images.githubusercontent.com/951776/46568455-748b1b00-c945-11e8-80fc-8603d07aba94.png">

+ http://energia.nu/download/ shows release 1.8.7E20

<img width="1440" alt="capture 2018-10-06 a 08 53 47" src="https://user-images.githubusercontent.com/951776/46568457-79e86580-c945-11e8-8a9b-a6db242e1170.png">

**Comment by robertinant** [comment]
All is in sync now. I forgot to push a couple changes.
